### PR TITLE
added support to modifyRequestHeaders

### PR DESCRIPTION
**Pull request by kamyweb**
based on https://github.com/getferdi/ferdi/pull/639

### Description
- Origin header was not being sent in the requests that searches users using Google APIs from Franz's webview.
- Add ability for recipes to add headers in any ongoing request from their respective webviews.
- Add ability to copy the host from Referer header, to match origin/referer headers
- Add headers for specific patterns of urls. This can be used to send different headers for different URLs in a recipe's context.
- Add check to identify if the method modifyRequestHeaders is implemented by recipes.
- Send IPC message from models/Service.js to the main process to set the headers if the method is implemented
- Receive the IPC message in index.js and add headers using session.fromPartition(<PartitionName>).webRequest.onBeforeSendHeaders method
- Changes to the Gmail / Hangouts / GoogleChat recipe have been added to the corresponding repo.

### Motivation and Context
Fixes external google services used inside gmail like: user autocomplete https://github.com/meetfranz/franz/issues/2081 , calendar invitation details https://github.com/meetfranz/franz/issues/2083 and others

### How Has This Been Tested?
Tested in local linux ubuntu 21.10 dev environment.
Based on franz 5.7.0

index.js of gmail recipe:
```
"use strict";

module.exports = Franz => class Gmail extends Franz {
  modifyRequestHeaders() {
                        return [{
                                headers: {
                                        'origin': 'RefererHost'
                                },
                                requestFilters: {
                                        urls: [
                                        '*://people-pa.clients6.google.com/*', '*://clients6.google.com/drive/*', '*://clients6.google.com/gmail/*', '*://signaler-pa.clients6.google.com/*', '*://addons-pa.clients6.google.com/*',
                                        '*://chat-pa.clients6.google.com/*','*://clients6.google.com/voice/*', '*://hangouts.google.com/*',
                                        '*://peoplestack-pa.clients6.google.com/*', '*://calendar-pa.clients6.google.com/*', '*://play.google.com/*']
                                }
                        }]
  }

};
```

### Screenshots:
from this
image
to this
image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ npm run lint`).

### CODE REVIEW

**Comment by albertobaselga** [comment]
@kamyweb Thanks for finding the solution. When can this fix be applied?? thanks

**Comment by kamyweb** [comment]
> @kamyweb Thanks for finding the solution. When can this fix be applied?? thanks

I don't know if there is still someone reviewing the PR like @adlk 
Looking the insights of this repo seems not maintained from months
I will open a PR on recipe repo that is more active

**Comment by hadees** [comment]
Im running into the same issue trying to add support for [AirMessage](https://airmessage.org/) for Web.

It needs a google login and google is basically rejecting it with a 403 for not having a referer header.  Im not entirely clear why Google doesn't complain about its own services which seem to use the same login but I guess its a security thing or something.

**Review by adlk — APPROVED** [review]
Great work @kamyweb 🙌

**Pull request merged**
