### PR TITLE
🐛📧 — Fix small email validation bug.

### PR DESCRIPTION
**Pull request by Snuggle**
### Description

I can't use my 100% valid email address with Franz, meaning that the email validation is incorrect and doesn't follow the appropriate standards.

### Motivation and Context

I can't change my email to `^-^@Snuggi.es`, the same that I use for GitHub, through the Franz application.
image

However, if I login and change it through the website I don't have an issue. It also updates within the application.

image

image

### How Has This Been Tested?

I tested the regex on https://regex101.com. There might be more email addresses incorrectly marked as invalid but I'm not sure how Franz should be rewritten to allow them all to work as they should. As far as I know, the best practice is just to check if it has a `@` and looks somewhat sane, then just send a confirmation email to check if it actually works.

Here's a relevant talk on email validation (Apologies for the bad audio):
https://www.youtube.com/watch?v=xxX81WmXjPg

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@adlk we should probably use `validator.isEmail` from https://www.npmjs.com/package/validator instead!

**Comment by adlk** [comment]
@DominikGuzei good idea! It also works well with @Snuggle's email.
https://runkit.com/adlk/5cf81bf9d403d1001a9d8106

**Comment by Snuggle** [comment]
I have not a clue how to import libraries within this project but I've given it a try! :blush: 
Could I please ask how to test this outside of CI, since I don't know if this is correct or not. :two_hearts:

**Comment by Snuggle** [comment]
Running `npx lerna bootstrap` updated the `package-lock.json` with a couple dependencies (Including `validator.js`). Should all of this be committed? Why did it add a dependency called "@meetfranz/theme"?

image

**Comment by DominikGuzei** [comment]
Thanks for the update @Snuggle your code looks good but i need to make some minor changes to make it work 👍 i will create a separate branch since i cannot commit to yours 😉

**Comment by Snuggle** [comment]
@DominikGuzei I just turned on "Allow edits from maintainers." I didn't realise that was off. :stuck_out_tongue:

**Comment by DominikGuzei** [comment]
Thanks @Snuggle, it's already done now but for next time 😉

**Comment by DominikGuzei** [comment]
We will add you as contributor to the changelog 🥇

**Comment by Snuggle** [comment]
Thanks! ♥️

**Pull request closed without merging**
