### PR TITLE
[ci skip] Fix `brew` command in README.md

### PR DESCRIPTION
**Pull request by Rabattkarte**
### Description
Fix `brew` command, as seen on: https://formulae.brew.sh/cask/franz

### Motivation and Context
`brew` syntax changed.

### How Has This Been Tested?
I installed Franz that way.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by eyallior** [comment]
OT - why the hell there's no way to report a bug in this program?

**Comment by JTCozart** [comment]
> OT - why the hell there's no way to report a bug in this program?

I have found that getting support, reporting bugs, etc is not possible with this program. This is why I have discontinued my paid subscription. It is unfortunate as the app has so much potential.

**Comment by Rabattkarte** [comment]
I'm happily using https://github.com/getferdi/ferdi now.

I will close this PR and delete the associated branch. Those emails about off topic discussions and the lack of interest for contribution by the maintainer is enough for this decision.

**Comment by Gaboris** [comment]
> I'm happily using https://github.com/getferdi/ferdi now.

Hey @Rabattkarte I hope I'm not gonna be annoying, but just as a heads up that Ferdi has officially been discontinued and won't be getting any new updates both in fixes and security patches.

Consider taking a look at [Ferdium](https://github.com/ferdium/ferdium-app) our hard fork of Ferdi with a bunch of important fixes, improvements and the most up to date security patches. 👍

P.S.: We are still in Beta, but our official Stable release is almost finished.

**Comment by tonyrobertcook** [comment]
> > OT - why the hell there's no way to report a bug in this program?
> 
> I have found that getting support, reporting bugs, etc is not possible with this program. This is why I have discontinued my paid subscription. It is unfortunate as the app has so much potential.

I have the same issues!!

**Pull request closed without merging**
