### PR TITLE
Fix minimized window focusing

### LINKED ISSUE #1300: "Show Franz" and clicking on notifications should unminimize window on Linux
**Describe the bug**
When you receive a notification in Linux (Ubuntu 18.04) for a new message and main window is minimized, clicking on that new message should unminimize Franz and show the new message in the relevant application.

Similarly, when Franz's window is minimized clicking on "Show Franz" in systray should bring its window to the front  

**To Reproduce**
1. Minimize Franz's window
2. Wait for new message
3. Click on the notification 
4. Nothing happens

or 

1. Minimize Franz's window
2. Click Franz's tray icon and select "**Show Franz**"
3. Nothing happens

**Expected behavior**
Window should be unminimized and brought to the front. When window is not minimized but not on the front, it should be brought to the front.
Everything works as expected when window is closed to systray 

**Desktop:**
 - OS: Ubuntu 18.04.2 LTS
 - Version 5.0.0 
 - Release: 4.0.4 / linux / x64

**Additional context**
I don't know if this is related but when Franz is closed to systray clicking on Franz icon in dock (so from system perspective, running *_franz_* command again, should behave as "**Show Franz**" action from systray. Right now, nothing happens

### PR DESCRIPTION
**Pull request by skoruppa**
Trying to fix #1300 by myself. Adding Window.restore() and Window.focus() helps addressing minimized window

### CODE REVIEW

**Comment by adlk** [comment]
@skoruppa please add specific testing instructions

**Comment by skoruppa** [comment]
@adlk I think I can just copy here what I have already wrote in #1300
Three cases:

### Case 1
- Minimize Franz's window
- Wait for new message
- Click on the notification
- Franz's window should be unminimized and brought to the front. Additionally the service from which notification came should be focused

### Case 2
- Minimize Franz's window
- Click Franz's tray icon and select "Show Franz"
- Franz's window should be unminimized and brought to the front

### Case 3
- Close Franz's window to tray icon
- Try to run Franz again from launcher/app menu
- Franz's window should be unminimized and brought to the front

**Comment by adlk** [comment]
OS was Ubuntu 18.04.2 LTS?

**Comment by skoruppa** [comment]
exactly

**Comment by adlk** [comment]
I've just tested this on Windows and adding `mainWindow.restore()` leads to unwanted side effects.
E.g. if you have maximized your window and want to reopen it `restore` will unmaximize the window. So please, do not remove the OS checks.

**Comment by skoruppa** [comment]
Oh, I didn't check that but there is exactly same behavior on Linux. However, I still insist to leave `mainWindow.restore()` there. Maybe we could just check if window is minimized with `mainWindow.isMinimized()` before we restore it?

**Comment by adlk** [comment]
LGTM :shipit: 

thanks for your effort!

**Pull request merged**
