### PR TITLE
[Proposal] Case-insensitive sorting of recipes in Dashboard

### PR DESCRIPTION
**Pull request by koma-private**
### Description

Currently recipes are sorted by case-sensitive alphabetical order and services which name begin with lower case letter come after services with upper case letter.

### Motivation and Context
To enable users to pick up a recipe from Dashboard more efficiently

### How Has This Been Tested?
Tested by "yarn run dev & yarn start"

### Screenshots (if appropriate):
sorting

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [ ] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by koma-private** [comment]
I think there is more smarter way than my code ;)

**Comment by adlk** [comment]
I believe we should coordinate better as this can be achieved on the server and does not require a code change in the client.
We should definitely use the slack channel for such things more often.

Oh boy, now I feel really bad.

**Comment by koma-private** [comment]
I sincerely apologize for making you bad about the recent my pull request.
I just misunderstood that code review and debate process will go on Github after my proposal. 
I have no intend to ignore users and your will, I'm just a tester and the final decision is in your hands. I'm respecting your work as talking with you on Slack. Now I noticed I should have posted to Slack channel at 1st after your pointing out. Sorry.

**Comment by adlk** [comment]
Oh please don't worry. I'm actually sorry that we can't use the work you've put in – no one likes to waste time. 😄 
TBH it's actually great that this happened because based on this, we can streamline our processes.

**Pull request closed without merging**
