### PR TITLE
Upgrade package.json

### PR DESCRIPTION
**Pull request by mhatvan**
### Description
Since a lot of packages were behind even two or more major versions and a lot of vulnerabilites were found with `npm audit`, I took the opportunity to upgrade the `package.json` file.  

### Motivation and Context
Issue can be found here: #1410 

### How Has This Been Tested?
Tested on Ubuntu 19.04.
Didn't encounter any errors in the app that could've been introduced by the version changes. 

### Changes
* All packages were upgraded to the latest version except for `react-router` and  `mobx-react-router` because i was not able to get it back up and running after upgrading to v5.
* I didn't upgrade to `electron` v5 because it produces node-gyp errors when running `npx electron-rebuild`.
* went from ~80 down to 41 vulnerabilities reported by `npm audit`.
* `gulp-server-livereload` is responsible for most of the vulnerabilities that still exist (last github activity in 2016). In my opinion, it should be removed from dependencies and another library introduced instead.

### Checklist:

- [ ] My code follows the code style of this project (run `$ yarn lint`).

No new eslint issues introduced with this MR, but I was not able to successfully run `yarn lint`, since there are a lot of eslint errors and warnings on the current develop branch already.

When are they going to be fixed?

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@mhatvan the appveyor build fails with eslint errors: https://ci.appveyor.com/project/adlk/franz/builds/24318172

**Comment by mhatvan** [comment]
@DominikGuzei yes I was aware of that but didn't realize where the lint errors came from since I didn't change the files that reported errors.

After taking another look now, I realized that the errors are only reported after upgrading `eslint-plugin-import` and `eslint-plugin-react`.
In the respective libraries changelog files I saw that the version upgrade led to specific cases of `import/no-cycle` and `react/no-array-index-key` being correctly triggered now.

I changed both rules from error to warning severity, it can be merged now. 

Hopefully there will be some initiative from @adlk in the future to fix all linting errors (~154 problems reported as of now).

**Comment by DominikGuzei** [comment]
@mhatvan we discussed your PR today and decided that it does way too much at once to be safe for the product … but still, thank you for the contribution - we will start updating 2-3 dependencies per release and work our work through like that 👍

**Comment by mhatvan** [comment]
Sorry, but this is not acceptable for a PR that passes all checks and includes relevant changes that would be necessary to do one day anways. 
Of course you are not comfortable with this PR, because there are basically zero unit tests in the project, but going through the ~20 screens manually that the app has and check for errors should'nt be such a big deal. 

Maybe there is a chance to rethink this decision, and next time, notify contributors BEFORE they start working on an issue that it doesn't make sense, instead of after everything is finished :-1:

**Comment by DominikGuzei** [comment]
Yeah, sorry for that - we should have discussed it before 🙏  or even better: state that we will never do something like updating all dependencies in one go.

Please consider that Franz needs to work on 3 operating systems (which all behave slightly different) and the problem is not so much testing all logic (which we have to do anyway) but narrowing down the possible reasons for problems. Simply updating many packages to the latest version (often jumping 2-3 major versions) opens up too many possible failure scenarios for us. It's not fun having to debug weird edge-cases when the array of "things you changed" becomes too large.

But i agree, not having any tests is definitely part of the problem - something we will work on 👍

**Pull request closed without merging**
