### PR TITLE
Introducing Dark Mode theme.

### PR DESCRIPTION
**Pull request by guillecura**
##### Updated stylesheets

* Lint `scss` files
* Create new color variables
* Add the new `.theme_dark` styles

screen shot 2018-07-07 at 3 48 11 pm

##### Added settings dark mode toggle

* Add `darkMode` variable to templates
* Add settings option toggle

screen shot 2018-07-07 at 3 48 01 pm

### Motivation and Context

It was the piece missing to the Franz project.
Inspired by and basing the new color palette on the new OSX Mojave's Dark Mode.

_This upgrade is based on [JasonEtco](https://github.com/JasonEtco)'s PR, but in the process I updated every stylesheet, not just the sidebar 😉

### Screenshots

example

### CODE REVIEW

**Comment by x029a** [comment]
I've tested this locally, and merged this pr into my fork. Built, and distributed to a few friends who much prefer the darker color scheme. Next step would be darkening slack and telegram specifically for my self.

**Comment by guillecura** [comment]
Thanks @x029a! 😁
Btw, have my Slack account's sidebar darken with this color scheme;
`#1E1E1E,#383A3B,#3498db,#CED0D1,#383A3B,#CED0D1,#5bc0de,#5bc0de`
Just copy&paste it into the preferences panel!

**Comment by x029a** [comment]
Awesome, thanks! I work at Intuit, and a few of us were talking about this app in slack and looking for ways to improve it. The first obviously was dark mode, thanks to your hard work! You can download the binary or share it from my fork. It's the `5.1` release. Thanks again @guillecura!

**Comment by cmccandless** [comment]
@x029a I'm interested in getting your fork up and running, but am having issues configuring my environment. Are you able to make your pre-built package available for download? Maybe post the link in an issue in your fork?

**Comment by ngohungphuc** [comment]
@x029a could you build Windows version please

**Comment by cmccandless** [comment]
@x029a thanks! Actually, I could really use binaries for both Windows and Debian, if you don't mind.

**Comment by elkuku** [comment]
Another "dark" user here - big :+1: and :heart:

**Comment by alapo** [comment]
> Sure thing @cmccandless , you can download it here: [Franz-5.1.0-Dark-Mode](https://github.com/x029a/franz/releases/download/5.1.0/Franz-5.1.zip) . Hope that helps! That's an `osx` binary, I could build a `windows` binary for you if you'd like as well.

I would also love to see a windows version if you have it

**Comment by cmccandless** [comment]
Finally got my build issues resolved (on Linux; still having difficulties with Windows), so here's a Linux release: https://github.com/cmccandless/franz/releases/tag/v5.1.0-beta.1.

**Comment by guillecura** [comment]
Hey @x029a, what if we add a color customization setting? Something like a new theme but with some hex inputs to customize major components colors. Ror example: the dark-mode color settings, but sidebar background color.. 🤔

**Comment by ngohungphuc** [comment]
Cant build window version. Can someone help me with it. Thank you

**Comment by cmccandless** [comment]
@fearphage Unfortunately, I don't have the bandwidth to work on this actively. I got it working for my system (Ubuntu 16.04), but cannot guarantee functionality for anyone else. Since I do have a working build environment for Linux builds, I am happy to create a new Linux release if someone else wants to create a PR in my fork to fix bugs.

**Comment by indykoning** [comment]
I can't wait for this PR to be merged but please be sure to check as many of the checks as possible, this will probably speed up the approval process

**Comment by x029a** [comment]
Sorry everyone I was out for quite a while. Back at it now, and just catching up. I personally wouldn't mind taking over some of the work on this project if @adlk is okay with that and wants to add me as a maintainer I can help take care of some of this stuff, do some PRs, testing and merging. In the mean time sometime this week I can work on my fork, and build binaries for Linux, OSX, and Windows.

**Comment by Stanzilla** [comment]
Yeah otherwise we could just keep maintaining a fork, I've pinged @adlk a million times but he never responded, would be a bit annoying to migrate all pull requests but still better than a dead project :)

**Comment by garfolino** [comment]
> Sure thing @cmccandless , you can download it here: [Franz-5.1.0-Dark-Mode](https://github.com/x029a/franz/releases/download/5.1.0/Franz-5.1.zip) . Hope that helps! That's an `osx` binary, I could build a `windows` binary for you if you'd like as well.

This is great. But I can't turn the dark mode on. The slide goes to ON and back to off.

**Comment by MikeDabrowski** [comment]
I guess there are some people who started improving their forks and it would be nice to merge all those upgrades.Right now I see no point creating another PR here, as there already are I think 3 PRs with dark mode. How would we pick the best one ?

**Comment by alapo** [comment]
> I guess there are some people who started improving their forks and it would be nice to merge all those upgrades.Right now I see no point creating another PR here, as there already are I think 3 PRs with dark mode. How would we pick the best one ?

Would you happen to have compiled a version of your fork for Windows? I tried doing this myself but after watching several YouTube videos was unable to create an .exe. I would be happy to test it out and report any issues back to you.

**Comment by MikeDabrowski** [comment]
@alapo I created a release with my dark/transparent version here: https://github.com/MikeDabrowski/franz/releases/tag/v5.0.0-beta.19

Transparent one is not really useful right now, it needs transparent services and a way to set body background image. In my private build I added it manually and forgot to create interface for such feature ;) If you are interested I can do it later.

**Comment by fearphage** [comment]
There are a lot of changes in this PR that don't serve any purpose (largely in the css). There's a lot of property sorting and things that makes the PR appear a lot larger than it is. It also makes it difficult to find the actual changes and errors. I was working on a branch to revert some of the unnecessary changes and fix the build so it stops failing. It's just changes on top of this branch since I can't push to this user's branch.

**Comment by MikeDabrowski** [comment]
@fearphage  Here's another PR with dark mode and tests passing 

https://github.com/meetfranz/franz/pull/362 

Personally I'd like it to be more generic. But first of all we need someone to review and merge those PRs.

**Comment by SoyDiego** [comment]
Hi, sorry someone can help me how can I install the Dark Mode in Manjaro??
Thanks people!

**Comment by alapo** [comment]
> Hi, sorry someone can help me how can I install the Dark Mode in Manjaro Linux??
> Thanks people!

I will make a YouTube video over the weekend on how to do this and post it here.

**Comment by SoyDiego** [comment]
> > Hi, sorry someone can help me how can I install the Dark Mode in Manjaro Linux??
> > Thanks people!
> 
> I will make a YouTube video over the weekend on how to do this and post it here.

Ok, thanks @alapo. The only thing I could do, is change the background of menus. But I want to change the WhatsApp / Messenger background, etc ... I hate the white background.
I'll wait for your video, thanks!

**Comment by MikeDabrowski** [comment]
@SoyDiego To change background of apps you only need to edit them. No need for compilation etc. Just find their css and style it yourself. 

There are already done black themes for several of them so you can copy paste.
https://github.com/bloodf/franz-dark-telegram here is dark theme for telegram, you could start from there. I have several services ported to transparent as well. I could use some pull requests to make them black or add new ones. https://github.com/MikeDabrowski/franz-themed-recipes

**Comment by SoyDiego** [comment]
> @SoyDiego To change background of apps you only need to edit them. No need for compilation etc. Just find their css and style it yourself.
> 
> There are already done black themes for several of them so you can copy paste.
> https://github.com/bloodf/franz-dark-telegram here is dark theme for telegram, you could start from there. I have several services ported to transparent as well. I could use some pull requests to make them black or add new ones. https://github.com/MikeDabrowski/franz-themed-recipes

Ok thanks @MikeDabrowski and where is the Franz Directory in Linux? Do you know?
Sorry, i'm new in Linux...
Maybe is better if i wait the video of @alapo

**Comment by MikeDabrowski** [comment]
@SoyDiego  I don't know. Try searching with find for a file named webview.js. Path should be similar to 
`Franz\recipes\messenger\webview.js`

**Comment by SoyDiego** [comment]
> @SoyDiego I don't know. Try searching with find for a file named webview.js. Path should be similar to
> `Franz\recipes\messenger\webview.js`

Thanks again, I search Franz in my system disk and I found all this directories but none have folders "recipes" or "webview.js" or "whatsapp" or "messenger", etc...
deepinscreenshot_seleccionar area_20181112145314

**Comment by MikeDabrowski** [comment]
Ok maybe then try opening service's developer tools, go to sources and ctrl+p, type webview.js and check the paths to those files. Maybe one of them will hint you the location of recipes folder.

**Comment by SoyDiego** [comment]
> Ok maybe then try opening service's developer tools, go to sources and ctrl+p, type webview.js and check the paths to those files. Maybe one of them will hint you the location of recipes folder.

Great, i found it.
>/home/diego/.config/Franz/recipes

Now I will try modified the CSS. Thanks for all @MikeDabrowski

**Comment by MikeDabrowski** [comment]
@SoyDiego  If you succeed making them dark go ahead create PR to my repo.

**Comment by alapo** [comment]
@SoyDiego, @MikeDabrowski and others here is a quick YouTube video on how I was able to get dark mode with Franz. The video might help other newbies such as myself who are unfamiliar with how to do it. Full credit goes to Mike for his release and helping me troubleshoot. If any parts are unclear I am happy to make edits to the video and re-upload.

[Franz Dark Installation](https://www.youtube.com/watch?v=1C4gME-eCfU)

**Comment by Stanzilla** [comment]
@alapo empty recycle bin and restart computer? come on... 

You can just install Mike's version over your current one, don't need to delete anything.

**Comment by alapo** [comment]
> @alapo empty recycle bin and restart computer? come on...
> 
> You can just install Mike's version over your current one, don't need to delete anything.

Sorry @MikeDabrowski just a habit when installing programs. I will make an edit to the video and reupload tonight when I get back home. Let me know if you saw any other issues.

**Comment by SoyDiego** [comment]
> @SoyDiego, @MikeDabrowski and others here is a quick YouTube video on how I was able to get dark mode with Franz. The video might help other newbies such as myself who are unfamiliar with how to do it. Full credit goes to Mike for his release and helping me troubleshoot. If any parts are unclear I am happy to make edits to the video and re-upload.
> 
> [Franz Dark Installation](https://www.youtube.com/watch?v=1C4gME-eCfU)

Hi @Alapo, thanks for your video and your time.
In my opinion the video was a little confused for me, because in Linux I can't use and install the version of @MikeDabrowski .

But I found other solution and I could put the dark theme in Whatsapp.
Here the steps:

1) Download Whatsapp [darkTheme.css](https://github.com/bloodf/franz-dark-whatsapp/blob/master/darkTheme.css) .
2) Found the folder **recipes**, In **Linux** you can find it here: 

> /home/yourUser/.config/Franz/recipes

In **Windows** you can find it here:

>%appdata%\Franz

3) Paste the file downloaded darkTheme.css inside the folder **Whatsapp**.
4) Open the file **webview.js** and replace the line this:

> Franz.injectCSS(path.join(__dirname, 'services.css'));

for this:

> Franz.injectCSS(path.join(__dirname, 'darkTheme.css'));

AND THAT'S ALL! :)

**OPTIONAL**
This theme haven't background dark in the section icons/gif/stickers.

deepinscreenshot_seleccionar area_20181113194350


so I add CSS lines to modify this background. If you want, **add this lines in darkTheme.css**:

```
._1vDUw._1UbeR, .l90LN.GclUX, ._2rR_l._29nQu, ._24k3z, ._1rADT, ._3Seam._2e6ev, ._1ifyO, ._1vDUw._33zGE {
    background-color: var(--dark) !important;
}
```

**FINAL RESULT**

deepinscreenshot_seleccionar area_20181113194515

Sorry for my english, is not good.
And thanks for your comments and video because without them, i could not have the solution.

**Comment by MikeDabrowski** [comment]
@SoyDiego Whould you mind creating PR with those dark themes you found / modified in my repo here https://github.com/MikeDabrowski/franz-themed-recipes

**Comment by SoyDiego** [comment]
> @SoyDiego Whould you mind creating PR with those dark themes you found / modified in my repo here https://github.com/MikeDabrowski/franz-themed-recipes

Sorry Mike, i'm very very new in Git and i don't understand about Pull Request, If you guide me, we can do it. Again thanks.

**Comment by MikeDabrowski** [comment]
1. go to https://github.com/MikeDabrowski/franz-themed-recipes/tree/recipes-dark
this is new branch i created for you (you could too I think but that's for the sake of simplicity here)
2. create directory for whatsapp or go to already existing directory for other recipes.
3. create css file, name it as stated in instructions
4. save
5. create PR (button is somewhere visible) and select that branch (recipes-dark) to merge it to master

There you go, roughly these are the steps.

**Comment by SoyDiego** [comment]
>     1. go to https://github.com/MikeDabrowski/franz-themed-recipes/tree/recipes-dark
>        this is new branch i created for you (you could too I think but that's for the sake of simplicity here)
> 
>     2. create directory for whatsapp or go to already existing directory for other recipes.
> 
>     3. create css file, name it as stated in instructions
> 
>     4. save
> 
>     5. create PR (button is somewhere visible) and select that branch (recipes-dark) to merge it to master
> 
> 
> There you go, roughly these are the steps.

I don't know if i did well.
I must create a README.md with the instructions also?

**Comment by MikeDabrowski** [comment]
I can't see anything. And no you don't have to create readme, just css file or directory

**Comment by SoyDiego** [comment]
> I can't see anything. And no you don't have to create readme, just css file or directory

deepinscreenshot_seleccionar area_20181113204323

**Comment by adlk** [comment]
@guillecura exceptional work!
I'm closing this in favor of #1118

**Pull request closed without merging**
