### PR TITLE
[PR - WIP] Change tabs with mousewheel / scroll

### PR DESCRIPTION
**Pull request by Tribex**
Allows users to change to the next tab/service using the mouse wheel.
Scrolling down changes to the next tab. Scrolling up changes to the previous tab.
Consistent with the behavior of many applications, such as Chrome, Atom, and Sublime Text.

### Description
Adds an `onWheel` event to `TabBarSortableList.js` that fires `setActiveNext` and `setActivePrev` depending on scroll direction. `setActiveNext` and `setActivePrev` are now passed down through the component prop tree in the same way as `setActive` in order to reach the `TabBarSortableList` component.

### Motivation and Context
My primary method of changing tabs in most applications tends to be by scrolling on the tab bar. It allows for rapidly switching between two or more nearby tabs without needing to click them with any accuracy or use the keyboard.

### How Has This Been Tested?
**Testing Procedures**
- Start Franz with the development instructions listed in the readme.
- Log in and add more than one service.
- Scroll anywhere on the tabbar except the settings button in order to change tabs.

**Environment**
- Linux x64 (Arch)
- X11 Display Server

### Screenshots (if appropriate):
peek 2017-11-07 13-41

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by adlk** [comment]
If you add more services, the tabbar becomes scrollable. _(I'm aware that this isn't a UX best practice but necessary at the moment as we don't have service folders yet.)_ The proposed feature however, would override the default behaviour of the tab bar.

If an OS has smooth scrolling support (windows/osx), this will not work as trying to go to the next tab is actually jumping a few tabs. You can see in the gif as I try to scroll from one service to the next. I believe this could be fixed by throttling the scroll event but it might always feel a little off. 

As this seems to be a linux specific navigation feature, I'd like to add @mroeling, @YWJamesLin, @alecive to the discussion before we're enabling this just on linux.


.

**Comment by Tribex** [comment]
> If you add more services, the tabbar becomes scrollable. (I'm aware that this isn't a UX best practice but necessary at the moment as we don't have service folders yet.) The proposed feature however, would override the default behaviour of the tab bar.

Ah, right. Actually just ran into this now. Anyway, that's something that could be solved in a number of ways:
- Using a modifier key + scroll to scroll tabs. 
- Not scrolling tabs until the parent's `scrollY` position is fully at the top or bottom.
- Disabling tab scrolling when a scrollbar is needed.

>

**Comment by mroeling** [comment]
Actually, I'm not sure. 
Yes, the functionality would be equal to the way Chrome and task bar work (in Kubuntu that is). But it is not something I would look for or would enable specifically. 
However, I could imagine for a hard-core Unix user it is a should-have feature. I would not just add a modifier for making this possible on Unix. If the default way indeed would be without modifier, then that's the way it is/should be.

**Comment by adlk** [comment]
> - Using a modifier key + scroll to scroll tabs.

See @mroeling answer.

> - Not scrolling tabs until the parent's scrollY position is fully at the top or bottom.
> - Disabling tab scrolling when a scrollbar is needed.

Modifying feature behaviour based on content sounds pretty confusing. 

> Enabling this only on Linux would match Chrome's behavior, but at the same time it would be kind of sad to not have it on all platforms.

I am actually ok with leaving Windows and Mac users out as this is not a known navigation behaviour to them – every platform has its unique concepts and quirks.

**Comment by Tribex** [comment]
Perhaps it could be put behind a settings flag that's enabled by default on Linux?

**Comment by YWJamesLin** [comment]
> Perhaps it could be put behind a settings flag that's enabled by default on Linux?
Agree with this, being an optional feature.

Honestly, I'm not sure and have no opinion about this feature. Since I use a tile window manager (awesome), I mostly use keyboard to navigate between applications, recipes in franz included. Thus I have no experience about mouse navigation.

**Comment by Tribex** [comment]
@adlk's bonus question.
Most code editors and maybe half of available browsers have this. It's also common in most GTK3 apps with tabs. (See Nautilus.)

No support for tab scrolling is the only thing keeping me from using Firefox as my default browser. There was a legacy extension that added support for it, but it can't be ported to WebExtensions, so I have a sad.

**Comment by adlk** [comment]
Thanks for all the infos.
I think I'm good to say that we can add an Linux only option to the settings panel to enable this. Maybe even under a new headline called "Navigation" after "General". @Tribex can you take care of this? 

Before we are doing this we require a new solution to avoid having to scroll in the first place. I have planned to work on a few solutions in the upcoming weeks. I would suggest that we keep this PR open until everything else is resolved. 

**Todos:**
- [ ] Add option to settings
- [ ] Add language strings to en-US master file

**Comment by Tribex** [comment]
@adlk Got it. I'll take a look as soon as I can. Thanks!
Are you sure you'd prefer the settings option to be Linux-only, as opposed to trying to make it functional on Windows and macOS as well?

**Comment by adlk** [comment]
It's not just about making it work in smooth scroll environments. The actual issue is that we are adding a completely unknown navigation behaviour to those platforms. While I support customizable UX, I believe that fewer options are sometimes better. 

On top: In the upcoming releases there are quite a few new options planned and I want to keep it as simple as possible options that are clear for everyone.

Btw, is there something like smooth scroll any Linux desktop env?

**Comment by Tribex** [comment]
@adlk Ah, makes sense. Thanks for the clarification.

Honestly... Not sure. I don't usually work much outside of Linux, and usually don't notice scroll behaviors for content. (Kind of embarassing to admit.)

**Comment by mroeling** [comment]
Seems it is not activated by default, but possible to activate: 
https://askubuntu.com/questions/966898/ubuntu-17-10-natural-scrolling

**Comment by adlk** [comment]
In that case, smooth scroll should be handled anyway.

**Comment by alecive** [comment]
Yes, natural scrolling in ubuntu has been added since 12.04 I believe.

**Comment by adlk** [comment]
@Tribex any updates on this one?

**Comment by Tribex** [comment]
@adlk Nope, been too busy with work-related... work.

Sorry. :/

**Pull request closed without merging**
