### PR TITLE
[PR] Dark Mode

### LINKED ISSUE #49: Dark Sidebar
Love the sidebar for services, can you please give us a dark mode for it? All of the services I use essentially are running in dark modes themselves and this bright grey sidebar is a serious eyesore.

### PR DESCRIPTION
**Pull request by JasonEtco**
### Description
Dark Mode 🦇 🌔 🎉 This is an MVP of what should eventually be a more holistic, app-wide change (right now it just changes the sidebar colors). I've added a toggle in the settings under Appearance, and modified the colors in the sidebar appropriately. I do think that this should be merged in the meantime, since building out the "dark theme" will be much easier once the logic has been added.

**Note**: I'm not sure how the i18n stuff works within this project. In the settings it renders as `!!!Dark Mode`, which I understand to mean that there is no available translation?

image

### Motivation and Context
Fixes #49. It's been the only thing that hasn't totally sold me on Franz since this afternoon when I was first introduced to it, so I'm happy it wasn't too difficult to implement 😄 

### How Has This Been Tested?
There aren't any tests in the repo, so I've just meandered around on my own within the app.

### Screenshots (if appropriate):
image

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ yarn lint`).
- [x] I have updated the documentation accordingly.

☝️ Not sure if this should be documented?

### CODE REVIEW

**Comment by haraldox** [comment]
great work, we will review this soon and / or provide our own implementation if the community is positive...

**Comment by alecive** [comment]
@haraldox any news on this?

**Comment by EnergyFusion** [comment]
Hi is there anything happening with this? I would really like this feature.

**Comment by buriedcable** [comment]
waiting to happen

**Comment by JSR-Gaming-x** [comment]
This would be awesome!

**Comment by Wouter0100** [comment]
Nearly 4 months further, not merged yet? Any idea when it will be merged, as the community seems positive.

**Comment by ronneke1996** [comment]
@adlk Sorry for mentioning, but any news on if this is going to get merged?

**Comment by whitfin** [comment]
@JasonEtco it looks like this is going to be accepted based on the approvals above... want to update your branch to fix up the conflicts? :)

**Comment by JasonEtco** [comment]
@whitfin those approvals aren't from maintainers of the project so while its nice to know people approve of it, its not really meaningful 🤷‍♂️

Quite a lot has changed since I opened this PR and I don't feel comfortable trying to wade through the conflicts (nor do I have the bandwidth for it). Maintainers, y'all are welcome to take over this branch and make whatever changes are needed, or close it out if it isn't a priority.

**Comment by alecive** [comment]
@whitfin actually, it looks like this PR will never be merged. Which is sad. It seems like Franz is not under active development any more : last commit from @adlk dates back to more than two weeks ago, whereas last commit from @haraldox is almost one and a half month ago.

**Comment by nickimola** [comment]
@alecive what you mean with not under development anymore? I saw that there's a "pro" mode, i don't think the development can be stopped whenever they want to, especially if they have some paying users (i'm not one of them, i'm just curious about your statement) :)

**Comment by Wouter0100** [comment]
I saw a comment in Slack that @adlk is currently OOO and will be back when.. he's back. No need to worry - yet.

**Comment by Cahl-Dee** [comment]
I also add styling to the title bar since I'm on Windows, and when I open up Franz, I hit, ctrl+alt+i and run this quick script:
`var cssStyle = document.createElement('style');
cssStyle.type = 'text/css';
var minCss = '#ReactVirtualized__Grid,#electron-app-title-bar,.list-item,.menu-pane,.sidebar,.toolbar-dropdown.open .button-component{background:#222!important;box-shadow:1px 0 5px rgba(0,0,0,.38)!important}#electron-app-title-bar,.list-item,.toolbar-dropdown.open .button-component{color:#d3d3d3!important}.tab-item.is-active{border-left:4px solid rgba(255,255,255,.4);background:rgba(255,255,255,.15)}',
 rules = document.createTextNode(minCss);
cssStyle.appendChild(rules);
document.getElementsByTagName("head")[0].appendChild(cssStyle);`

For anyone interested in the beautified CSS (yes, I used !important):
`#electron-app-title-bar,
 .toolbar-dropdown.open .button-component,
 .menu-pane,
 .list-item,
 #electron-app-title-bar,
 #ReactVirtualized__Grid,
 .sidebar{
    background:#222 !important;
    box-shadow:1px 0 5px rgba(0,0,0,.38) !important;
}
.toolbar-dropdown.open .button-component,
  #electron-app-title-bar,
  .list-item{
    color: lightgray !important;
}
.tab-item.is-active{
  border-left:4px solid rgba(255,255,255,.4);
  background:rgba(255,255,255,.15);
}`

**Comment by elkuku** [comment]
@Cahl-Dee your solution is pretty neat - thanks for sharing.

**Comment by Luminus** [comment]
Howdy folks, just checking to see if this is going to get merged.

**Comment by dalemccutcheon** [comment]
any luck with this?

**Comment by jaminroe** [comment]
Looking forward to this!

**Comment by SoyDiego** [comment]
> **Edit:** I've added styling for the settings menu as well.
> 
> When I open up Franz, I hit, ctrl+alt+i and run this quick script (I also add styling to the title bar since I'm on Windows):
> `var cssStyle = document.createElement('style'); cssStyle.type = 'text/css'; var minCss = 'body{color:#d0d0d0}.badge{color:#000}#electron-app-title-bar,.list-item,.settings-navigation .settings-navigation__link,.toolbar-dropdown.open .button-component{color:#d3d3d3!important}#ReactVirtualized__Grid,#electron-app-title-bar,.list-item,.menu-pane,.settings .account .account__box,.settings-navigation,.settings__close,.settings__controls,.settings__header,.sidebar,.toolbar-dropdown.open .button-component{background:#222!important;box-shadow:1px 0 5px rgba(0,0,0,.38)!important}.settings__main{background:#333!important}.tab-item.is-active{border-left:4px solid rgba(255,255,255,.4);background:rgba(255,255,255,.15)}.service-table .service-table__row:hover,.settings .settings__close:hover,.settings-navigation .settings-navigation__link:hover{background:#000!important}', rules = document.createTextNode(minCss); cssStyle.appendChild(rules); document.getElementsByTagName("head")[0].appendChild(cssStyle);`

Great, working perfect in the menus @Cahl-Dee 
But is possible change the Whatsapp background and colors? I hate all white :(
Thanks!

**Comment by Gy0m** [comment]
@StanSvec Same Here

**Pull request closed without merging**
