### PR TITLE
Fixed spelling mistake and swapped word

### PR DESCRIPTION
**Pull request by haveneersrobin**
### Description
Fixed spelling mistake and swapped word for 'better' alternative.

### Motivation and Context
Past participle of 'updaten' is 'geüpdatet' (http://www.mijnwoordenboek.nl/werkwoord/updaten)
"Wijzigingen" sounds better and is more often used as "veranderingen" for "changes".

### How Has This Been Tested?
/

### Screenshots (if appropriate):
+
### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:
- [x] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by Wouter0100** [comment]
Hmm.. I don't think the whole "Je veranderingen werden bewaard" sentence is correct. Shouldn't it be something like "Je veranderingen zijn opgeslagen", looking to the English translation?

**Comment by haveneersrobin** [comment]
@Wouter0100 I only changed 'veranderingen' to 'wijzigingen' because the word seems more appropriate.
The English sentence is "Your changes have been saved", which (imo) could be translated to both, without having a significant difference in meaning.
- Je wijzigingen werden bewaard
- Je wijzigingen zijn opgeslagen (although I seem to prefer this one, I'll change it)
For me, the word "veranderingen" didn't seem right.

**Comment by Wouter0100** [comment]
Excuse me, I copied the wrong sentence. I also preferred `wijzigingen`.

**Comment by adlk** [comment]
Thanks for all the work you guys are putting into this! ❤️

**Pull request merged**
