### PR TITLE
Translate missing texts in the Polish translation

### PR DESCRIPTION
**Pull request by Gelio**
Some texts in the Polish translation were in English. I translated them to Polish.

I am a native Polish speaker so I also went through all other translations and slightly reworded a few.

### Description

If you have any questions about some texts, let me know. I will be more than happy to help 🙂 

BTW. Good job on the existing translations 😄 I see that they have been generated automatically and they are pretty good 😄 I especially liked the one about the dark mode:

> Przejdź na Ciemną Stronę

which translates to 

> Join the Dark Side

😄 I had a laugh on this one

### Motivation and Context

Polish translations contained sentences in English

### How Has This Been Tested?

I used my native Polish speaking skills 😄 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [ ] My code follows the code style of this project (run `$ yarn lint`).

I do not think any of the above apply

### CODE REVIEW

**Comment by Glennmen** [comment]
@Gelio For translations I think you need to use: http://i18n.meetfranz.com/
Original thread about translations: https://github.com/meetfranz/franz/issues/39

**Comment by Gelio** [comment]
@Glennmen Too bad I did not find it earlier. I will contribute there. Thanks for giving me a hint 😄 I am going to close this PR.

Btw. did I miss the information that translation contributions should be done via the site you referenced? I just went through the repo and did not find it in the readme nor CONTRIBUTING.md. I suggest adding that information so there are no wasted efforts on PRs such as this one 🙂 

I am going to close this PR as it is not necessary

**Comment by Glennmen** [comment]
@Gelio I found it by "accident", I was also planning on making a PR for translations. You are 100% correct that it should be added to CONTRIBUTING.md

I also just now found this in the Franz application:
image

**Comment by Gelio** [comment]
@Glennmen Oh, alright. Thanks for letting me know! I missed it 😄

**Pull request closed without merging**
