### PR TITLE
Add Electron globalShortcut 'Alt+Shift+F' to toggle between 'Show/Hide Franz'

### PR DESCRIPTION
**Pull request by mhatvan**
### Description
Added shortcut Alt+Shift+F to toggle between 'Show/Hide Franz', which is a faster way then going to the System Bar Tray Icon and clicking it.

### Motivation and Context
Feature request can be found here: #1218

### How Has This Been Tested?
Tested on Ubuntu 18.10.
Verified with different applications that the global shortcut Alt+Shift+F doesn't collide with default shortcuts of the tested applications. 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by adlk** [comment]
@mhatvan  Thanks for adding this.

We thought about that for quite some time in the past. If we are going to add a global shortcut it must me customizable for the user as a global listener has so much potential for conflicts.

If you are willing to tackle this then I'm more than happy to write down the specs.

**Comment by mhatvan** [comment]
hey @adlk,

I also had in mind that we could define default global shortcuts and then let the user customize them, in case they use an application shortcut that collides with it or just for fun, but decided against it since I didn't want to do UI changes without your knowledge.

Yes, I want to tackle this and it would be great to have mockups or some other visual reference of how you imagine it to look like for the users.

**Comment by mhatvan** [comment]
@adlk any updates from your side so that I can start working on customizable shortcuts?

**Comment by mhatvan** [comment]
@adlk is there still any interest from your side to implement this? Otherwise I will close the PR.

**Pull request closed without merging**
