### PR TITLE
Icons and Description for Linux installation

### LINKED ISSUE #300: No program icon in taskbar
### Expected Behavior
Icon should be displayerd in taskbar

### Current Behavior
No icon is displayed

### Screenshots (if appropriate):
auswahl_20171118_14 43 57

### PR DESCRIPTION
**Pull request by antonpirker**
### Description

In the deb installer there is now a synopsis and a description displayed. (Explaining the user about what he/she is about to install)

Also fixed the Application icon in Ubuntu.

### Motivation and Context

Closes #300

### CODE REVIEW

**Comment by alecive** [comment]
What about not using a single svg image? Is there a reason to using all those files?

**Comment by antonpirker** [comment]
@alecive the reason: it works and it's the only way I know about. but if you have time you are welcome to update this and create a PR to use one svg file ;-)

**Comment by adlk** [comment]
@antonpirker thanks for taking care of this. Your PR is now merged and the update will be shipped with beta 15.

**Comment by idimopoulos** [comment]
Omg, I just checked this 4 minutes ago and went and manually downloaded the fork so that I get the icons and I was wondering when is it going to be merged :P Nice work :D

**Comment by Kuchiriel** [comment]
The icon in windows button in XFCE will appear in this release?

**Pull request merged**
