### PR TITLE
Do not strip www from custom urls

### PR DESCRIPTION
**Pull request by BeneStem**
Stripping www from the custom url causes some custom services to fail.
When there is no domain without www loading is not possible.

Resolves: #325

### CODE REVIEW

**Comment by BeneStem** [comment]
Will fix linting in a sec... sorry!

**Comment by adlk** [comment]
Awesome, thanks for your contribution.

**Comment by BeneStem** [comment]
No problem. Wasn‘t much of a deal :)

When will this be available in the beta 5?

**Comment by adlk** [comment]
If I'm able to resolve the main blocker (issues with SettingsStore) then it will be today or tomorrow.

**Comment by BeneStem** [comment]
Neat. Best of luck resolving the issue!

**Pull request merged**
