### PR TITLE
WIP: Franz and recipe theming

### PR DESCRIPTION
**Pull request by MikeDabrowski**
This PR enables Franz user to change theme in settings. Also contains other minor fixes and improvements.

### Description
This PR enables Franz user to change theme in settings. For now there are three basic themes - dark, regular, transparent-dark. Themes apply to Franz app, and also, in other [repository ](https://github.com/MikeDabrowski/franz-themed-recipes) I store themed recipes. In this PR changing Franz's theme also sets matching theme to installed recipes.

Be aware that I marked it as WIP, mainly because I removed analytics, which might be needed by original authors.

I'd love to hear some input from maintainers, maybe some hints, improvements.

### Motivation and Context
This PR was created because I dislike white themes. Also there are many users who share this dislike, and also couple open PRs with similar features. Only mine, however, is built in scss which allows easily new color schemes. Also it is much more advanced than simply changing css (see above).

### How Has This Been Tested?
II use it everyday, and tweak from time to time. Also there are few users who have tried my fork and have provided some input.

### Screenshots (if appropriate):
theme-transparent-dark-slack
theme-dark-slack

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ yarn lint`). Can't say that about previous commits.

### CODE REVIEW

**Comment by MikeDabrowski** [comment]
Ups, something broke...

**Comment by Stanzilla** [comment]
I *think* basing the PR against the `develop` branch would be the better idea.

**Comment by MikeDabrowski** [comment]
@Stanzilla That might be a good idea. I see I got some conflicts now. Also travis errors out on something I don't know how to change.

**Comment by MikeDabrowski** [comment]
I got lots of errors when running checks against develop branch. Most in the code I haven't event touched. 
@adlk would you find the time to look at this and help me solve it?

**Comment by Stanzilla** [comment]
To increase the chances of this getting merged, you should probably not include the changes that remove premium user limitations and analytics in this PR.

**Comment by MikeDabrowski** [comment]
@Stanzilla Thanks for the support. Since dark mode has been already included I doubt this PR will ever be merged, and the lack of input from original creator can only confirm it. I keep my fork with this changes, sometimes pull changes from master. If anyone is interested its all there. 

I don't want to close this PR. I'm open to cooperation. If original creator wants to add my features I will be happy to modify everything he sees need modifying. If not, I think its best he close this PR.

**Pull request closed without merging**
